package hibernate;
// Generated 2017-3-31 17:03:10 by Hibernate Tools 5.2.0.CR1

/**
 * Weixianyuan generated by hbm2java
 */
public class Weixianyuan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String jobActivity;
	private String badFactor;
	private String badEvent;
	private String rank;
	private String controlAction;
	private String yijian;
	private String accessory;
	private String projectName;

	public Weixianyuan() {
	}

	public Weixianyuan(String jobActivity, String badFactor, String badEvent, String rank, String controlAction,
			String yijian, String accessory, String projectName) {
		this.jobActivity = jobActivity;
		this.badFactor = badFactor;
		this.badEvent = badEvent;
		this.rank = rank;
		this.controlAction = controlAction;
		this.yijian = yijian;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getJobActivity() {
		return this.jobActivity;
	}

	public void setJobActivity(String jobActivity) {
		this.jobActivity = jobActivity;
	}

	public String getBadFactor() {
		return this.badFactor;
	}

	public void setBadFactor(String badFactor) {
		this.badFactor = badFactor;
	}

	public String getBadEvent() {
		return this.badEvent;
	}

	public void setBadEvent(String badEvent) {
		this.badEvent = badEvent;
	}

	public String getRank() {
		return this.rank;
	}

	public void setRank(String rank) {
		this.rank = rank;
	}

	public String getControlAction() {
		return this.controlAction;
	}

	public void setControlAction(String controlAction) {
		this.controlAction = controlAction;
	}

	public String getYijian() {
		return this.yijian;
	}

	public void setYijian(String yijian) {
		this.yijian = yijian;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
